[workspace]
authors = ["Pau Fernández <pau.fernandez@upc.edu>"]
channels = ["conda-forge"]
name = "src"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mypy = ">=1.15.0,<2"
graph-tool = ">=2.97,<3"
requests = ">=2.32.3,<3"
requests_cache = ">=0.4.13,<0.5"
aiohttp = ">=3.11.16,<4"
aiohttp-client-cache = ">=0.13.0,<0.14"
click = ">=8.1.8,<9"
